plugins:
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

exclude:      ['Gemfile', 'Gemfile.lock', 'README.md', 'config.ru', 'vendor']

languages:    ["es", "en", "val"]

sass:
  sass_dir:   css/_scss
  style:      compressed

assets:
  compress:
    css:      default
    js:       default
    img:      default

  autowrite:  true

  assets:
    - 'main.css'
    - '*.js'
    - '*.png'
    - '*.jpg'
    - '*.svg'
    - '*.ttf'
    - '*.woff'

  sources:
    - css
    - js
    - images

# ----- VERCEL -----
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.callorens.com/" # the base hostname & protocol for your site, e.g. http://example.com

# ------------------------

# Build settings
markdown:     kramdown

# Texts
main:
  title:      'Ca Llorens'
  titleTag:   'Ca Llorens'
  keywords:   'ca llorens callorens almuerzos paella asados asador bar restaurante valencia llombay carne ib√©rico iberico torraor almorsaret cremaet'

terms:
  title:      'Aviso Legal'
